# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: numbers
version: '0.0.0'
github: "modul/numbers"
license: MIT
author: "Remo Giermann"
maintainer: "Remo Giermann"
synopsis: Client interface to the numbersapi.com trivia database
description: Numbers can be used as a library or CLI to retrieve trivia about numbers from the open Numbers API.
category: API, Client, CLI

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - bytestring
  - http-conduit
  - attoparsec
  source-dirs: library

executables:
  numbers:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - numbers
    - bytestring
    - cmdargs
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-orphans

tests:
  numbers-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - numbers
    - tasty
    - tasty-hspec
    - tasty-discover
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
